-- Read the docs: https://www.lunarvim.org/docs/configuration
-- Video Tutorials: https://www.youtube.com/watch?v=sFA9kX-Ud_c&list=PLhoH5vyxr6QqGu0i7tt_XoVK9v-KvZ3m6
-- Forum: https://www.reddit.com/r/lunarvim/
-- Discord: https://discord.com/invite/Xb9B4Ny

reload("nepko.options")
reload("nepko.cppconfig")
-- reload("nepko.javaconfig")
-- reload("nepko.pyconfig")
reload("nepko.keymaps")
reload("nepko.vim-surround")
reload("nepko.mdPreview")
reload("nepko.hop")
reload("nepko.hop")
reload("nepko.lsp-signature")
reload("nostr")
reload("nepko.webdev-icons")
reload("nepko.plugins")
reload("nepko.lsp")
reload("nepko.neotest")
reload("nepko.surround")
reload("nepko.git")
reload("nepko.neogit")
reload("nepko.icons")
reload("nepko.diagnostics")
reload("nepko.lsp.*")
reload("nepko.nvim-ufo")
reload("nepko.indent-blankline")
reload("nepko.jsconfig")
reload("nepko.dap")
